[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

# -----------------------
# Host Testing
# -----------------------

[tasks.test-host]
dependencies = [
    # Add host tests here
]

# -----------------------
# Embedded Testing
# -----------------------

[tasks.test-device]
dependencies = [
    "test-temperature-board",
    "test-pressure-board",
    "test-strain-board",
    "test-common-arm",
]

[tasks.test-common-arm]
command = "cargo"
args = ["test", "-p", "common-arm", "${@}"]

[tasks.test-temperature-board]
command = "cargo"
args = ["test", "--bin", "phoenix", "${@}"]